# ***1. Import Libraries***

In [33]:
import pandas as pd
import numpy as np
import tensorflow as tf

# ***2. Check TensorFlow Version***

In [34]:
# Display TensorFlow version to ensure compatibility
tf.__version__

'2.17.0'

# ***3. Load the Dataset***

In [35]:
# Load the dataset and display its structure
dataset = pd.read_csv('/content/Churn_Modelling.csv')
print(dataset.head())  # Show first few rows for a quick overview


   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

# ***4. Split Dataset into Features (X) and Target Variable (y)***

In [36]:
# Select features and target from the dataset
# 'X' includes all features except the first three columns (customer data) and the last column (target)
# 'y' is the target variable indicating customer churn
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [37]:
print('x: ',X)
print('y: ',y)

x:  [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y:  [1 0 1 ... 1 1 0]


# ***5. Encode Categorical Data***

In [38]:
# Encode categorical variable 'Gender' as numerical values using LabelEncoder
from sklearn.preprocessing import LabelEncoder
labelenc = LabelEncoder()
X[:, 2] = labelenc.fit_transform(X[:, 2])
print(X)  # Check transformation

# Apply OneHotEncoder to 'Geography' column to avoid ordinal relationship
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columtran = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [1])],
    remainder='passthrough'
)
X = np.array(columtran.fit_transform(X))
print(X)  # Verify OneHotEncoding

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# ***6. Split Data into Training and Testing Sets***

In [39]:
from sklearn.model_selection import train_test_split #spliting the data into training set and test set
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state =0)

# ***7. Feature Scaling***

In [40]:
# Apply feature scaling to standardize features, improving model performance and training speed
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)  # Use same scaler to ensure consistency

# ***8. Build the ANN***

In [41]:
# Initialize the ANN model
ann = tf.keras.models.Sequential()

# Add input layer and first hidden layer with ReLU activation
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Add a second hidden layer to increase model capacity
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Add output layer with sigmoid activation to predict binary outcomes
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# ***9. Compile and Train the Model***

In [43]:
# Compile the ANN using binary crossentropy for binary classification
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model with 80 epochs and a batch size of 32
ann.fit(X_train, y_train, batch_size=32, epochs=80)


Epoch 1/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8616 - loss: 0.3357
Epoch 2/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8670 - loss: 0.3265
Epoch 3/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3364
Epoch 4/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8585 - loss: 0.3411
Epoch 5/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8604 - loss: 0.3384
Epoch 6/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8622 - loss: 0.3341
Epoch 7/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8586 - loss: 0.3334
Epoch 8/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8657 - loss: 0.3254
Epoch 9/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8497 - loss: 0.3576
Epoch 10/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8653 - loss: 0.3263
Epoch 11/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8560 - loss: 0.3461
Epoch 12/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

# ***10. Evaluate the Model***

In [44]:
# Evaluate the model's performance on the test set
test_loss, test_accuracy = ann.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test Accuracy: {test_accuracy}")


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8642 - loss: 0.3292
Test Loss: 0.33599549531936646, Test Accuracy: 0.8615000247955322
